[[build.buildpacks]]
uri = "https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest.git"

[[build.buildpacks]]
uri = "https://github.com/xrisk/heroku-opus.git"

[[build.buildpacks]]
uri = "heroku/python"
